Repository spring-cloud/spring-cloud-openfeign, pull requests merged in 2019-01, with the labels that each got.

#90 Support Multiple Clients Using The Same Service
  docs/src/main/asciidoc/spring-cloud-openfeign.adoc
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClient.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/SpringDecoderTests.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/invalid/FeignClientValidationTests.java
Labels: enhancement

#106 Upgrade feign-form to 3.5.0
  spring-cloud-openfeign-dependencies/pom.xml
Labels: in progress

#113 Fixes gh-107
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringEncoderTests.java
Labels: waiting-for-triage
