Repository spring-cloud/spring-cloud-openfeign, pull requests merged in 2024-09, with the labels that each got.

#1041 fix: defaultValue in additional-spring-configuration-metadata.json
  spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: documentation

#1050 Authorize with anonymous principal if principal name is null
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/security/OAuth2AccessTokenInterceptor.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/OAuth2AccessTokenInterceptorTests.java
Labels: bug

#1047 Adds ignorecase field to pageable spring
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SortJsonComponent.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SortJacksonModuleTests.java
Labels: enhancement

#1071 Make Content-Encoding configurable
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignClientEncodingProperties.java
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTests.java
Labels: bug

#1038 polishing FeignClientsRegistrar
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
Labels: task
