Repository spring-cloud/spring-cloud-openfeign, pull requests merged in 2024-05, with the labels that each got.

#1016 SpringMvcContract support parse params
  docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
  spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
Labels: enhancement

#1030 Register hints for superinterface methods
  spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/aot/FeignClientBeanFactoryInitializationAotProcessor.java
Labels: bug

#1027 Fix Reactive Support doc
  docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
Labels: documentation
